service:
  name: Adobe XD
  category: design
  status: sanctioned
  risk_level: low
network:
  domains:
  - adobe-xd.com
  - api.adobe-xd.com
  - app.adobe-xd.com
  - cdn.adobe-xd.com
  - static.adobe-xd.com
  - adobe-xd.io
  ip_ranges:
  - 151.164.0.0/16
  - 151.11.0.0/16
traffic_patterns:
  web_paths:
  - /dashboard
  - /
  - /designs
  - /projects
  - /login
  - /assets
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.88
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.001
