service:
  name: Akamai
  category: development
  status: sanctioned
  risk_level: low
network:
  domains:
  - akamai.com
  - '*.akamai.com'
  - api.akamai.com
  - app.akamai.com
  - akamai.io
  ip_ranges:
  - 192.69.0.0/16
  - 172.54.0.0/16
  - 104.183.0.0/16
traffic_patterns:
  web_paths:
  - /dashboard
  - /build
  - /login
  - /deploy
  - /api/v2
  - /repos
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
  api_endpoints:
  - /api/v1/auth
  - /api/v1/users
  - /api/v1/data
  - /api/v1/development
activity:
  user_adoption_rate: 0.84
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.001
