service:
  name: Cal.com
  category: communication
  status: unsanctioned
  risk_level: low
network:
  domains:
  - calcom.com
  - '*.calcom.com'
  - api.calcom.com
  - app.calcom.com
  - meet.calcom.com
  - chat.calcom.com
  ip_ranges:
  - 151.191.0.0/16
  - 172.219.0.0/16
  - 172.67.0.0/16
traffic_patterns:
  web_paths:
  - /contacts
  - /dashboard
  - /
  - /call
  - /api/v1
  - /recordings
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile:
    - Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15
    - Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36
activity:
  user_adoption_rate: 0.27
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.14
