service:
  name: Codecov
  category: development
  status: unsanctioned
  risk_level: low
network:
  domains:
  - codecov.com
  - '*.codecov.com'
  ip_ranges:
  - 185.47.0.0/16
  - 151.29.0.0/16
traffic_patterns:
  web_paths:
  - /api/v1
  - /build
  - /api/v2
  - /repos
  - /login
  - /code
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
  api_endpoints:
  - /api/v1/auth
  - /api/v1/users
  - /api/v1/data
  - /api/v1/development
activity:
  user_adoption_rate: 0.17
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.22
