service:
  name: Constant Contact
  category: marketing
  status: unsanctioned
  risk_level: medium
network:
  domains:
  - constant-contact.com
  - '*.constant-contact.com'
  - api.constant-contact.com
  - app.constant-contact.com
  - constant-contact.io
  ip_ranges:
  - 172.185.0.0/16
  - 172.100.0.0/16
traffic_patterns:
  web_paths:
  - /analytics
  - /dashboard
  - /lists
  - /api/v1
  - /api/v2
  - /campaigns
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.12
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.11
  dlp_triggers:
  - pattern: SSN|[0-9]{3}-[0-9]{2}-[0-9]{4}
    action: block
    rate: 0.01
