service:
  name: Crazy Egg
  category: analytics
  status: unsanctioned
  risk_level: medium
network:
  domains:
  - crazy-egg.com
  - cdn.crazy-egg.com
  - static.crazy-egg.com
  - crazy-egg.io
  ip_ranges:
  - 104.23.0.0/16
  - 13.68.0.0/16
traffic_patterns:
  web_paths:
  - /data
  - /
  - /reports
  - /api/v1
  - /metrics
  - /api/v2
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
  api_endpoints:
  - /api/v1/auth
  - /api/v1/users
  - /api/v1/data
  - /api/v1/analytics
activity:
  user_adoption_rate: 0.1
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.16
  dlp_triggers:
  - pattern: SSN|[0-9]{3}-[0-9]{2}-[0-9]{4}
    action: block
    rate: 0.01
