service:
  name: Deezer
  category: entertainment
  status: blocked
  risk_level: high
network:
  domains:
  - deezer.com
  - '*.deezer.com'
  - deezer.io
  ip_ranges:
  - 185.236.0.0/16
  - 185.66.0.0/16
traffic_patterns:
  web_paths:
  - /library
  - /play
  - /watch
  - /dashboard
  - /login
  - /api/v2
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile:
    - Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15
    - Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36
activity:
  user_adoption_rate: 0.03
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
  attempt_patterns:
    persistent_users: 0.2
    max_attempts_per_day: 5
security_events:
  block_rate: 1.0
  alerts:
    repeated_attempts:
      threshold: 3
      window_minutes: 60
      severity: high
