service:
  name: Docusign
  category: legal
  status: sanctioned
  risk_level: low
network:
  domains:
  - docusign.com
  - '*.docusign.com'
  - docusign.io
  ip_ranges:
  - 151.188.0.0/16
  - 13.162.0.0/16
  - 52.45.0.0/16
traffic_patterns:
  web_paths:
  - /dashboard
  - /signatures
  - /api/v1
  - /compliance
  - /api/v2
  - /contracts
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.73
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.001
