service:
  name: ExaVault
  category: file_transfer
  status: unsanctioned
  risk_level: medium
network:
  domains:
  - exavault.com
  - api.exavault.com
  - app.exavault.com
  - cdn.exavault.com
  - static.exavault.com
  - files.exavault.com
  - download.exavault.com
  ip_ranges:
  - 52.172.0.0/16
  - 185.54.0.0/16
  - 13.225.0.0/16
traffic_patterns:
  web_paths:
  - /dashboard
  - /send
  - /
  - /api/v2
  - /receive
  - /download
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.06
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.18
  dlp_triggers:
  - pattern: SSN|[0-9]{3}-[0-9]{2}-[0-9]{4}
    action: block
    rate: 0.01
