service:
  name: GMX
  category: email
  status: unsanctioned
  risk_level: high
network:
  domains:
  - gmx.com
  - '*.gmx.com'
  - cdn.gmx.com
  - static.gmx.com
  - mail.gmx.com
  - smtp.gmx.com
  - imap.gmx.com
  ip_ranges:
  - 172.110.0.0/16
traffic_patterns:
  web_paths:
  - /sent
  - /
  - /login
  - /api/v1
  - /inbox
  - /compose
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile:
    - Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15
    - Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36
activity:
  user_adoption_rate: 0.06
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
    email_send:
      weight: 0.2
      avg_per_hour: 5
      size_bytes: 5000
    email_read:
      weight: 0.3
      avg_per_hour: 20
    attachment_download:
      weight: 0.1
      avg_size_mb: 2
security_events:
  block_rate: 0.38
  dlp_triggers:
  - pattern: SSN|[0-9]{3}-[0-9]{2}-[0-9]{4}
    action: block
    rate: 0.01
