service:
  name: Khan Academy
  category: education
  status: unsanctioned
  risk_level: low
network:
  domains:
  - khan-academy.com
  - '*.khan-academy.com'
  - api.khan-academy.com
  - app.khan-academy.com
  - cdn.khan-academy.com
  - static.khan-academy.com
  - khan-academy.io
  ip_ranges:
  - 104.30.0.0/16
  - 54.187.0.0/16
traffic_patterns:
  web_paths:
  - /assignments
  - /
  - /api/v1
  - /api/v2
  - /courses
  - /lessons
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.19
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.38
