service:
  name: MediaFire
  category: cloud_storage
  status: blocked
  risk_level: high
network:
  domains:
  - mediafire.com
  - '*.mediafire.com'
  - api.mediafire.com
  - app.mediafire.com
  - files.mediafire.com
  - download.mediafire.com
  - mediafire.io
  ip_ranges:
  - 151.143.0.0/16
  - 151.202.0.0/16
traffic_patterns:
  web_paths:
  - /
  - /sync
  - /api/v1
  - /share
  - /api/v2
  - /download
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.06
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
    file_upload:
      weight: 0.2
      avg_size_mb: 10
      size_std_dev: 5
    file_download:
      weight: 0.2
      avg_size_mb: 8
      size_std_dev: 4
    folder_browse:
      weight: 0.1
      avg_duration_seconds: 20
  attempt_patterns:
    persistent_users: 0.2
    max_attempts_per_day: 5
security_events:
  block_rate: 1.0
  alerts:
    repeated_attempts:
      threshold: 3
      window_minutes: 60
      severity: high
