service:
  name: Microsoft 365
  category: productivity
  status: sanctioned
  risk_level: low
network:
  domains:
  - microsoft-365.com
  - '*.microsoft-365.com'
  - api.microsoft-365.com
  - app.microsoft-365.com
  - cdn.microsoft-365.com
  - static.microsoft-365.com
  - microsoft-365.io
  ip_ranges:
  - 52.209.0.0/16
  - 172.20.0.0/16
traffic_patterns:
  web_paths:
  - /dashboard
  - /
  - /projects
  - /tasks
  - /login
  - /calendar
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
  api_endpoints:
  - /api/v1/auth
  - /api/v1/users
  - /api/v1/data
  - /api/v1/productivity
activity:
  user_adoption_rate: 0.68
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
    document_edit:
      weight: 0.3
      avg_duration_seconds: 300
    task_create:
      weight: 0.1
      avg_per_hour: 5
    task_update:
      weight: 0.1
      avg_per_hour: 10
security_events:
  block_rate: 0.001
