service:
  name: n8n
  category: api_tools
  status: unsanctioned
  risk_level: medium
network:
  domains:
  - n8n.com
  - '*.n8n.com'
  - api.n8n.com
  - app.n8n.com
  ip_ranges:
  - 52.122.0.0/16
  - 104.148.0.0/16
  - 185.70.0.0/16
traffic_patterns:
  web_paths:
  - /login
  - /dashboard
  - /api/v2
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.1
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.33
  dlp_triggers:
  - pattern: SSN|[0-9]{3}-[0-9]{2}-[0-9]{4}
    action: block
    rate: 0.01
