service:
  name: Notion
  category: productivity
  status: unsanctioned
  risk_level: medium
network:
  domains:
  - notion.com
  - api.notion.com
  - app.notion.com
  - cdn.notion.com
  - static.notion.com
  ip_ranges:
  - 151.165.0.0/16
  - 151.112.0.0/16
  - 52.91.0.0/16
traffic_patterns:
  web_paths:
  - /dashboard
  - /
  - /projects
  - /tasks
  - /login
  - /documents
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
  api_endpoints:
  - /api/v1/auth
  - /api/v1/users
  - /api/v1/data
  - /api/v1/productivity
activity:
  user_adoption_rate: 0.21
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
    document_edit:
      weight: 0.3
      avg_duration_seconds: 300
    task_create:
      weight: 0.1
      avg_per_hour: 5
    task_update:
      weight: 0.1
      avg_per_hour: 10
security_events:
  block_rate: 0.12
  dlp_triggers:
  - pattern: SSN|[0-9]{3}-[0-9]{2}-[0-9]{4}
    action: block
    rate: 0.01
