service:
  name: OpenAI API
  category: ai_ml
  status: unsanctioned
  risk_level: high
network:
  domains:
  - openai-api.com
  - '*.openai-api.com'
  ip_ranges:
  - 104.101.0.0/16
  - 52.127.0.0/16
  - 104.72.0.0/16
traffic_patterns:
  web_paths:
  - /generate
  - /
  - /models
  - /api/v1
  - /inference
  - /api/v2
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.23
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.17
  dlp_triggers:
  - pattern: SSN|[0-9]{3}-[0-9]{2}-[0-9]{4}
    action: block
    rate: 0.01
