service:
  name: Plausible
  category: analytics
  status: unsanctioned
  risk_level: low
network:
  domains:
  - plausible.com
  - '*.plausible.com'
  - cdn.plausible.com
  - static.plausible.com
  ip_ranges:
  - 104.145.0.0/16
  - 185.190.0.0/16
traffic_patterns:
  web_paths:
  - /
  - /reports
  - /login
  - /dashboards
  - /insights
  - /api/v2
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
  api_endpoints:
  - /api/v1/auth
  - /api/v1/users
  - /api/v1/data
  - /api/v1/analytics
activity:
  user_adoption_rate: 0.08
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.24
