service:
  name: ShareFile
  category: file_transfer
  status: sanctioned
  risk_level: low
network:
  domains:
  - sharefile.com
  - cdn.sharefile.com
  - static.sharefile.com
  - files.sharefile.com
  - download.sharefile.com
  - sharefile.io
  ip_ranges:
  - 185.243.0.0/16
  - 13.221.0.0/16
traffic_patterns:
  web_paths:
  - /send
  - /
  - /api/v1
  - /share
  - /api/v2
  - /receive
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.68
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.001
