service:
  name: Splunk
  category: analytics
  status: sanctioned
  risk_level: low
network:
  domains:
  - splunk.com
  - api.splunk.com
  - app.splunk.com
  ip_ranges:
  - 52.28.0.0/16
  - 54.102.0.0/16
  - 192.102.0.0/16
traffic_patterns:
  web_paths:
  - /data
  - /dashboard
  - /
  - /login
  - /dashboards
  - /insights
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
  api_endpoints:
  - /api/v1/auth
  - /api/v1/users
  - /api/v1/data
  - /api/v1/analytics
activity:
  user_adoption_rate: 0.74
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.001
