service:
  name: Stack Overflow
  category: social_media
  status: sanctioned
  risk_level: low
network:
  domains:
  - stack-overflow.com
  - api.stack-overflow.com
  - app.stack-overflow.com
  ip_ranges:
  - 54.3.0.0/16
  - 185.247.0.0/16
traffic_patterns:
  web_paths:
  - /messages
  - /dashboard
  - /
  - /explore
  - /posts
  - /api/v2
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile:
    - Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15
    - Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36
activity:
  user_adoption_rate: 0.82
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.001
