service:
  name: SugarSync
  category: cloud_storage
  status: unsanctioned
  risk_level: medium
network:
  domains:
  - sugarsync.com
  - '*.sugarsync.com'
  - api.sugarsync.com
  - app.sugarsync.com
  - cdn.sugarsync.com
  - static.sugarsync.com
  - files.sugarsync.com
  - download.sugarsync.com
  ip_ranges:
  - 13.205.0.0/16
  - 52.57.0.0/16
traffic_patterns:
  web_paths:
  - /dashboard
  - /
  - /sync
  - /login
  - /share
  - /download
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.18
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
    file_upload:
      weight: 0.2
      avg_size_mb: 10
      size_std_dev: 5
    file_download:
      weight: 0.2
      avg_size_mb: 8
      size_std_dev: 4
    folder_browse:
      weight: 0.1
      avg_duration_seconds: 20
security_events:
  block_rate: 0.14
  dlp_triggers:
  - pattern: SSN|[0-9]{3}-[0-9]{2}-[0-9]{4}
    action: block
    rate: 0.01
