service:
  name: The Guardian
  category: news
  status: unsanctioned
  risk_level: low
network:
  domains:
  - the-guardian.com
  - '*.the-guardian.com'
  - api.the-guardian.com
  - app.the-guardian.com
  - the-guardian.io
  ip_ranges:
  - 104.127.0.0/16
  - 52.246.0.0/16
traffic_patterns:
  web_paths:
  - /login
  - /api/v1
  - /dashboard
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.08
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.25
