service:
  name: Tidio
  category: support
  status: unsanctioned
  risk_level: medium
network:
  domains:
  - tidio.com
  - '*.tidio.com'
  - api.tidio.com
  - app.tidio.com
  - cdn.tidio.com
  - static.tidio.com
  ip_ranges:
  - 54.192.0.0/16
  - 13.181.0.0/16
  - 54.81.0.0/16
traffic_patterns:
  web_paths:
  - /chat
  - /dashboard
  - /tickets
  - /api/v1
  - /community
  - /api/v2
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.16
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.23
  dlp_triggers:
  - pattern: SSN|[0-9]{3}-[0-9]{2}-[0-9]{4}
    action: block
    rate: 0.01
