service:
  name: Udacity
  category: education
  status: unsanctioned
  risk_level: low
network:
  domains:
  - udacity.com
  - '*.udacity.com'
  - udacity.io
  ip_ranges:
  - 185.15.0.0/16
  - 172.185.0.0/16
  - 192.196.0.0/16
traffic_patterns:
  web_paths:
  - /library
  - /grades
  - /dashboard
  - /assignments
  - /
  - /api/v1
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.19
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.37
