service:
  name: Vectr
  category: design
  status: unsanctioned
  risk_level: low
network:
  domains:
  - vectr.com
  - '*.vectr.com'
  - api.vectr.com
  - app.vectr.com
  - vectr.io
  ip_ranges:
  - 185.14.0.0/16
traffic_patterns:
  web_paths:
  - /prototypes
  - /
  - /assets
  - /api/v1
  - /api/v2
  - /collaborate
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.11
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.29
