service:
  name: WeChat
  category: collaboration
  status: blocked
  risk_level: high
network:
  domains:
  - wechat.com
  - '*.wechat.com'
  - api.wechat.com
  - app.wechat.com
  - meet.wechat.com
  - chat.wechat.com
  ip_ranges:
  - 172.60.0.0/16
traffic_patterns:
  web_paths:
  - /messages
  - /
  - /api/v1
  - /api/v2
  - /teams
  - /workspace
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.07
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
    message_send:
      weight: 0.3
      avg_per_hour: 20
      size_bytes: 200
    message_read:
      weight: 0.2
      avg_per_hour: 50
    file_share:
      weight: 0.05
      avg_size_mb: 5
  attempt_patterns:
    persistent_users: 0.2
    max_attempts_per_day: 5
security_events:
  block_rate: 1.0
  alerts:
    repeated_attempts:
      threshold: 3
      window_minutes: 60
      severity: high
