service:
  name: When2meet
  category: communication
  status: unsanctioned
  risk_level: medium
network:
  domains:
  - when2meet.com
  - '*.when2meet.com'
  - api.when2meet.com
  - app.when2meet.com
  - cdn.when2meet.com
  - static.when2meet.com
  - meet.when2meet.com
  - chat.when2meet.com
  - when2meet.io
  ip_ranges:
  - 54.74.0.0/16
traffic_patterns:
  web_paths:
  - /contacts
  - /
  - /call
  - /api/v1
  - /api/v2
  - /video
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile:
    - Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15
    - Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36
activity:
  user_adoption_rate: 0.23
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
security_events:
  block_rate: 0.32
  dlp_triggers:
  - pattern: SSN|[0-9]{3}-[0-9]{2}-[0-9]{4}
    action: block
    rate: 0.01
