service:
  name: Zippyshare
  category: file_transfer
  status: blocked
  risk_level: high
network:
  domains:
  - zippyshare.com
  - '*.zippyshare.com'
  - api.zippyshare.com
  - app.zippyshare.com
  - files.zippyshare.com
  - download.zippyshare.com
  - zippyshare.io
  ip_ranges:
  - 192.38.0.0/16
  - 13.175.0.0/16
traffic_patterns:
  web_paths:
  - /transfer
  - /dashboard
  - /send
  - /login
  - /share
  - /api/v2
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.02
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
  attempt_patterns:
    persistent_users: 0.2
    max_attempts_per_day: 5
security_events:
  block_rate: 1.0
  alerts:
    repeated_attempts:
      threshold: 3
      window_minutes: 60
      severity: high
