service:
  name: Zoom
  category: collaboration
  status: sanctioned
  risk_level: low
network:
  domains:
  - zoom.com
  - '*.zoom.com'
  - meet.zoom.com
  - chat.zoom.com
  ip_ranges:
  - 52.158.0.0/16
  - 54.164.0.0/16
  - 52.61.0.0/16
traffic_patterns:
  web_paths:
  - /
  - /channels
  - /login
  - /api/v1
  - /meet
  - /teams
  user_agents:
    desktop:
    - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36
    mobile: []
activity:
  user_adoption_rate: 0.64
  actions:
    page_view:
      weight: 0.3
      avg_duration_seconds: 30
    api_call:
      weight: 0.2
      avg_per_hour: 10
    message_send:
      weight: 0.3
      avg_per_hour: 20
      size_bytes: 200
    message_read:
      weight: 0.2
      avg_per_hour: 50
    file_share:
      weight: 0.05
      avg_size_mb: 5
security_events:
  block_rate: 0.001
